export default [
  {
    id: '1',
    name: 'Shopping Cart',
    imageName: 'project-1.jpg',
    tag: 'MERN',
    link: 'https://gitlab.com/xthazudp/shopping-cart.git',
  },
  {
    id: '2',
    name: 'Shopping App',
    imageName: 'shoppingApp.jpg',
    tag: 'MERN',
    link: 'https://gitlab.com/xthazudp/shoppingapp',
  },
  {
    id: '3',
    name: 'Node Farm',
    imageName: 'project-3.jpg',
    tag: 'NODEJS',
    link: 'https://github.com/xthazudp/nodeFarm',
  },
  {
    id: '4',
    name: 'Natour',
    imageName: 'project-4.jpg',
    tag: 'CSS/SASS',
    link: 'https://github.com/xthazudp/Natours',
  },
  {
    id: '5',
    name: 'Forkify',
    imageName: 'project-5.jpg',
    tag: 'JAVASCRIPT',
    link: 'https://github.com/xthazudp/forkify',
  },
  {
    id: '6',
    name: 'DOM Pig Game',
    imageName: 'project-6.jpg',
    tag: 'JAVASCRIPT',
    link: 'https://github.com/xthazudp/DOM-pig-game',
  },
  {
    id: '7',
    name: 'Budgety',
    imageName: 'project-7.jpg',
    tag: 'JAVASCRIPT',
    link: 'https://github.com/xthazudp/Budgety',
  },
  {
    id: '8',
    name: 'Disease Prediction',
    imageName: 'project-8.jpg',
    tag: 'PYTHON/AI',
    link: 'https://github.com/xthazudp/Disease-Prediction-System',
  },
  {
    id: '9',
    name: 'Nepali Sign Language Prediction',
    imageName: 'project-8.jpg',
    tag: 'PYTHON/AI',
    link: 'https://github.com/xthazudp/NepaliSignLanguageRecognition',
  },
];
